"""Pytest CI gate: one test per conformance section.

The vectors are the pre-existing failing spec (written before this code,
generated by a different system) — running this code against them is
test-first by construction. A red section fails CI.
"""
import pytest

from fu_mesh_conformance.harness import run

REPORT = run()
SECTIONS = sorted({r.section for r in REPORT.results})


@pytest.mark.parametrize("section", SECTIONS)
def test_section(section):
    fails = [r for r in REPORT.results if r.section == section and not r.ok]
    assert not fails, "\n".join(
        f"{r.section}.{r.key}: expected={r.expected!r} actual={r.actual!r} "
        f"cause={r.cause} source={r.source}"
        for r in fails
    )


def test_overall_pass():
    assert REPORT.passed
